Corrigiendo escena y prefabs para funcionar correctamente
hay-espacio-en-el-taco/Alerta-Minerva pull request #77
Opened 2017-01-28 16:10 UTC by Xotl

Corrigiendo escena y prefabs para funcionar correctamente

2017-01-29 15:52 UTC, Freihart512 commented
@cmedinilla  puedes por favor revisar esta PR ya que tiene un error en los sonidos cuando un monstruo toca el edifico

2017-01-29 19:01 UTC, Xotl commented
Bueno, ese issue no tiene nada que ver con este PR, sino con los Prefabs de algunos monstruos.

2017-01-30 14:28 UTC, cmedinilla commented
¿Que pasa cuando un monstruo toca un edificio?, no deberia sonar nada :s  @Freihart512

2017-01-30 14:38 UTC, Freihart512 commented
@cmedinilla el problema es que cuando baje el PR para probar truena en algo relacionado a sonido no podría confirmar  que es exactamente por la noche les comparto el error

@Xotl  comente esto puesto que al no poder testear la PR no deberíamos hacer merge ya que si quieren que se haga de una vez lo hago pero quedaría fallando en master

2017-03-05 19:20 UTC, Xotl commented
@Freihart512, @lordzero0000 , @cmedinilla... ya corregí lo de las referencias nulas para que no truene la escena. Hagan review.

2017-05-23 16:41 UTC, metalvegetarianoprogresivo requested changes
No funciona aun.

2018-10-25 00:04 UTC, closed without merging